package model;
// Generated Apr 13, 2018 1:57:34 PM by Hibernate Tools 4.3.1



/**
 * Detail generated by hbm2java
 */
public class Detail  implements java.io.Serializable {


     private DetailId id;
     private Jabatan jabatan;
     private JenisLembur jenisLembur;
     private Long tarif;

    public Detail() {
    }

	
    public Detail(DetailId id, Jabatan jabatan, JenisLembur jenisLembur) {
        this.id = id;
        this.jabatan = jabatan;
        this.jenisLembur = jenisLembur;
    }
    public Detail(DetailId id, Jabatan jabatan, JenisLembur jenisLembur, Long tarif) {
       this.id = id;
       this.jabatan = jabatan;
       this.jenisLembur = jenisLembur;
       this.tarif = tarif;
    }
   
    public DetailId getId() {
        return this.id;
    }
    
    public void setId(DetailId id) {
        this.id = id;
    }
    public Jabatan getJabatan() {
        return this.jabatan;
    }
    
    public void setJabatan(Jabatan jabatan) {
        this.jabatan = jabatan;
    }
    public JenisLembur getJenisLembur() {
        return this.jenisLembur;
    }
    
    public void setJenisLembur(JenisLembur jenisLembur) {
        this.jenisLembur = jenisLembur;
    }
    public Long getTarif() {
        return this.tarif;
    }
    
    public void setTarif(Long tarif) {
        this.tarif = tarif;
    }




}


