package model;
// Generated Apr 13, 2018 1:57:34 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DetailLembur generated by hbm2java
 */
public class DetailLembur  implements java.io.Serializable {


     private String kdDetailLembur;
     private PegawaiMii pegawaiMii;
     private JenisLembur jenisLembur;
     private Date tglLembur;

    public DetailLembur() {
    }

	
    public DetailLembur(String kdDetailLembur, PegawaiMii pegawaiMii, JenisLembur jenisLembur) {
        this.kdDetailLembur = kdDetailLembur;
        this.pegawaiMii = pegawaiMii;
        this.jenisLembur = jenisLembur;
    }
    public DetailLembur(String kdDetailLembur, PegawaiMii pegawaiMii, JenisLembur jenisLembur, Date tglLembur) {
       this.kdDetailLembur = kdDetailLembur;
       this.pegawaiMii = pegawaiMii;
       this.jenisLembur = jenisLembur;
       this.tglLembur = tglLembur;
    }
   
    public String getKdDetailLembur() {
        return this.kdDetailLembur;
    }
    
    public void setKdDetailLembur(String kdDetailLembur) {
        this.kdDetailLembur = kdDetailLembur;
    }
    public PegawaiMii getPegawaiMii() {
        return this.pegawaiMii;
    }
    
    public void setPegawaiMii(PegawaiMii pegawaiMii) {
        this.pegawaiMii = pegawaiMii;
    }
    public JenisLembur getJenisLembur() {
        return this.jenisLembur;
    }
    
    public void setJenisLembur(JenisLembur jenisLembur) {
        this.jenisLembur = jenisLembur;
    }
    public Date getTglLembur() {
        return this.tglLembur;
    }
    
    public void setTglLembur(Date tglLembur) {
        this.tglLembur = tglLembur;
    }




}


