package model;
// Generated Apr 13, 2018 1:57:34 PM by Hibernate Tools 4.3.1



/**
 * DetailId generated by hbm2java
 */
public class DetailId  implements java.io.Serializable {


     private String kdJabatan;
     private String kdLembur;

    public DetailId() {
    }

    public DetailId(String kdJabatan, String kdLembur) {
       this.kdJabatan = kdJabatan;
       this.kdLembur = kdLembur;
    }
   
    public String getKdJabatan() {
        return this.kdJabatan;
    }
    
    public void setKdJabatan(String kdJabatan) {
        this.kdJabatan = kdJabatan;
    }
    public String getKdLembur() {
        return this.kdLembur;
    }
    
    public void setKdLembur(String kdLembur) {
        this.kdLembur = kdLembur;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetailId) ) return false;
		 DetailId castOther = ( DetailId ) other; 
         
		 return ( (this.getKdJabatan()==castOther.getKdJabatan()) || ( this.getKdJabatan()!=null && castOther.getKdJabatan()!=null && this.getKdJabatan().equals(castOther.getKdJabatan()) ) )
 && ( (this.getKdLembur()==castOther.getKdLembur()) || ( this.getKdLembur()!=null && castOther.getKdLembur()!=null && this.getKdLembur().equals(castOther.getKdLembur()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getKdJabatan() == null ? 0 : this.getKdJabatan().hashCode() );
         result = 37 * result + ( getKdLembur() == null ? 0 : this.getKdLembur().hashCode() );
         return result;
   }   


}


