package model;
// Generated Apr 13, 2018 1:57:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Jabatan generated by hbm2java
 */
public class Jabatan  implements java.io.Serializable {


     private String kdJabatan;
     private String namaJabatan;
     private Set<Detail> details = new HashSet<Detail>(0);
     private Set<PegawaiMii> pegawaiMiis = new HashSet<PegawaiMii>(0);

    public Jabatan() {
    }

	
    public Jabatan(String kdJabatan) {
        this.kdJabatan = kdJabatan;
    }
    public Jabatan(String kdJabatan, String namaJabatan, Set<Detail> details, Set<PegawaiMii> pegawaiMiis) {
       this.kdJabatan = kdJabatan;
       this.namaJabatan = namaJabatan;
       this.details = details;
       this.pegawaiMiis = pegawaiMiis;
    }
   
    public String getKdJabatan() {
        return this.kdJabatan;
    }
    
    public void setKdJabatan(String kdJabatan) {
        this.kdJabatan = kdJabatan;
    }
    public String getNamaJabatan() {
        return this.namaJabatan;
    }
    
    public void setNamaJabatan(String namaJabatan) {
        this.namaJabatan = namaJabatan;
    }
    public Set<Detail> getDetails() {
        return this.details;
    }
    
    public void setDetails(Set<Detail> details) {
        this.details = details;
    }
    public Set<PegawaiMii> getPegawaiMiis() {
        return this.pegawaiMiis;
    }
    
    public void setPegawaiMiis(Set<PegawaiMii> pegawaiMiis) {
        this.pegawaiMiis = pegawaiMiis;
    }




}


