package model;
// Generated Apr 13, 2018 1:57:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * JenisLembur generated by hbm2java
 */
public class JenisLembur  implements java.io.Serializable {


     private String kdLembur;
     private Byte lamaLembur;
     private Set<Detail> details = new HashSet<Detail>(0);
     private Set<DetailLembur> detailLemburs = new HashSet<DetailLembur>(0);

    public JenisLembur() {
    }

	
    public JenisLembur(String kdLembur) {
        this.kdLembur = kdLembur;
    }
    public JenisLembur(String kdLembur, Byte lamaLembur, Set<Detail> details, Set<DetailLembur> detailLemburs) {
       this.kdLembur = kdLembur;
       this.lamaLembur = lamaLembur;
       this.details = details;
       this.detailLemburs = detailLemburs;
    }
   
    public String getKdLembur() {
        return this.kdLembur;
    }
    
    public void setKdLembur(String kdLembur) {
        this.kdLembur = kdLembur;
    }
    public Byte getLamaLembur() {
        return this.lamaLembur;
    }
    
    public void setLamaLembur(Byte lamaLembur) {
        this.lamaLembur = lamaLembur;
    }
    public Set<Detail> getDetails() {
        return this.details;
    }
    
    public void setDetails(Set<Detail> details) {
        this.details = details;
    }
    public Set<DetailLembur> getDetailLemburs() {
        return this.detailLemburs;
    }
    
    public void setDetailLemburs(Set<DetailLembur> detailLemburs) {
        this.detailLemburs = detailLemburs;
    }




}


