package model;
// Generated Apr 13, 2018 1:57:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PegawaiMii generated by hbm2java
 */
public class PegawaiMii  implements java.io.Serializable {


     private long nip;
     private Jabatan jabatan;
     private String nama;
     private String jk;
     private String alamat;
     private Date tglLahir;
     private String tmptLahir;
     private Set<DetailLembur> detailLemburs = new HashSet<DetailLembur>(0);

    public PegawaiMii() {
    }

	
    public PegawaiMii(long nip, Jabatan jabatan) {
        this.nip = nip;
        this.jabatan = jabatan;
    }
    public PegawaiMii(long nip, Jabatan jabatan, String nama, String jk, String alamat, Date tglLahir, String tmptLahir, Set<DetailLembur> detailLemburs) {
       this.nip = nip;
       this.jabatan = jabatan;
       this.nama = nama;
       this.jk = jk;
       this.alamat = alamat;
       this.tglLahir = tglLahir;
       this.tmptLahir = tmptLahir;
       this.detailLemburs = detailLemburs;
    }
   
    public long getNip() {
        return this.nip;
    }
    
    public void setNip(long nip) {
        this.nip = nip;
    }
    public Jabatan getJabatan() {
        return this.jabatan;
    }
    
    public void setJabatan(Jabatan jabatan) {
        this.jabatan = jabatan;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getJk() {
        return this.jk;
    }
    
    public void setJk(String jk) {
        this.jk = jk;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public Date getTglLahir() {
        return this.tglLahir;
    }
    
    public void setTglLahir(Date tglLahir) {
        this.tglLahir = tglLahir;
    }
    public String getTmptLahir() {
        return this.tmptLahir;
    }
    
    public void setTmptLahir(String tmptLahir) {
        this.tmptLahir = tmptLahir;
    }
    public Set<DetailLembur> getDetailLemburs() {
        return this.detailLemburs;
    }
    
    public void setDetailLemburs(Set<DetailLembur> detailLemburs) {
        this.detailLemburs = detailLemburs;
    }




}


